services:
  - type: web
    name: sistema-tickets-django
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && python manage.py loaddata initial_data.json && gunicorn ticket_system.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: ticket_system.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: django-insecure-^^f_@ffd8+31l#$sgzrskijgt3q3ja5qr-7puqwuhju&m61c#)
